// Crypto++DLL dynamic-link library.
// Copyright (c) 1995-2009 by Wei Dai,
// All rights reserved.

// pch.cpp - source file that includes just the standard includes

// initially generated by AfxScratch v1.1.4778 on 06.06.2009 at 12:08:32
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

//////////////////////////////////////////////////////////////////////////////////////////////
// PCH includes

#include "pch.h"

//////////////////////////////////////////////////////////////////////////////////////////////
// linker options

#if defined(_MSC_VER) && (_MSC_VER < 1300)
#pragma comment(linker, "/opt:ref")
// all references to DLL discarded by /opt:ref
#pragma comment(linker, "/ignore:4089")
#endif   // _MSC_VER

//////////////////////////////////////////////////////////////////////////////////////////////
// import libraries

#pragma comment(lib, "ws2_32.lib")

//////////////////////////////////////////////////////////////////////////////////////////////
// manifest dependencies

#if !defined(_LIB)
#pragma comment(linker, "/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='x86' publicKeyToken='6595b64144ccf1df' language='*'\"")
#if defined(_DEBUG)
#pragma comment(linker, "/manifestdependency:\"type='win32' name='Microsoft.VC90.DebugCRT' version='9.0.21022.8' processorArchitecture='x86' publicKeyToken='1fc8b3b9a1e18e3b'\"")
#elif defined(CRYPTOPP_PRIVATE_CRT)
#pragma comment(linker, "/manifestdependency:\"type='win32' name='Microsoft.VC90.PrivateCRT' version='9.0.21022.8' processorArchitecture='x86' publicKeyToken='1fc8b3b9a1e18e3b'\"")
#else
#pragma comment(linker, "/manifestdependency:\"type='win32' name='Microsoft.VC90.CRT' version='9.0.21022.8' processorArchitecture='x86' publicKeyToken='1fc8b3b9a1e18e3b'\"")
#endif   // _DEBUG
#endif   // _LIB

// end of file
