// Used by ListOptionsCtrlRes.rc

#define IDS_LISTOPTIONS_OK              0x80B0
#define IDS_LISTOPTIONS_TRUE            0x80B1
#define IDS_LISTOPTIONS_FALSE           0x80B2
#define IDS_LISTOPTIONS_ATTRIBUTE_TEXT  0x80B3
#define IDS_LISTOPTIONS_ATTRIBUTE_VALUE 0x80B4
#define IDS_LISTOPTIONS_DEFAULT_FOLDER_CAPTION 0x80B5
#define IDS_LISTOPTIONS_DEFAULT_FILE_CAPTION 0x80B6
#define IDS_LISTOPTIONS_DEFAULT_FILE_EXTENSION_FILTER 0x80B7
