// Used by ScintillaWrappersRes.rc

#define IDD_SCINTILLA_FINDDLGORD        0x80D1
#define IDD_SCINTILLA_REPLACEDLGORD     0x80D2

#define IDC_REGULAR_EXPRESSION          101

#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 0x80D3
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 0x80D4
