// Used by TreeOptionsCtrlRes.rc

#define IDS_TREEOPTIONS_OK              0x80C0
#define IDS_TREEOPTIONS_TRUE            0x80C1
#define IDS_TREEOPTIONS_FALSE           0x80C2
#define IDS_TREEOPTIONS_DEFAULT_FOLDER_CAPTION 0x80C3
#define IDS_TREEOPTIONS_DEFAULT_FILE_CAPTION 0x80C4
#define IDS_TREEOPTIONS_DEFAULT_FILE_EXTENSION_FILTER 0x80C5
