// Used by XTaskDialogRes.rc

#define IDI_XTASKDIALOG_COMMANDLINK     0x80A0
#define IDI_XTASKDIALOG_SHIELD          0x80A1
#define IDI_XTASKDIALOG_HOT_COMMANDLINK 0x80A2
#define IDI_XTASKDIALOG_ERROR           0x80A3
#define IDI_XTASKDIALOG_WARNING         0x80A4
#define IDI_XTASKDIALOG_INFORMATION     0x80A5

#define IDS_XTASKDIALOG_BUTTON_CAPTION0 0x80A6
#define IDS_XTASKDIALOG_BUTTON_CAPTION1 0x80A7
#define IDS_XTASKDIALOG_BUTTON_CAPTION2 0x80A8
#define IDS_XTASKDIALOG_BUTTON_CAPTION3 0x80A9
#define IDS_XTASKDIALOG_BUTTON_CAPTION4 0x80AA
#define IDS_XTASKDIALOG_BUTTON_CAPTION5 0x80AB
