// Brainchild dynamic-link library.
// Copyright (c) 1993-2005 by Jan van den Baard,
// All rights reserved.
// Enchancements (c) 2008 by Elijah Zarezky.

// stdafx.c - source file that includes just the standard includes

// initially generated by AfxScratch v1.0.3839 on 01.04.2008 at 19:49:24
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

// import libraries
#pragma comment(lib, "User32.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "Gdi32.lib")
#pragma comment(lib, "Advapi32.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "comctl32.lib")
#pragma comment(lib, "shlwapi.lib")
#pragma comment(lib, "Comdlg32.lib")

// linker options
#if defined(_MSC_VER) && (_MSC_VER < 1300)
#pragma comment(linker, "/ignore:4089")		// all references to DLL discarded by /opt:ref
#endif	// _MSC_VER

// end of file
