// atlmfc71 library.
// Copyright (c) 2005 by Elijah Zarezky,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes

// initially generated by AfxScratch v1.0.2461 on 21.01.2005 at 09:57:58
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// end of file
