// ClassLib library.
// Copyright (c) 2008 by Elijah Zarezky,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes

// initially generated by AfxScratch v1.0.3839 on 27.03.2008 at 08:21:03
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

// end of file
