//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ToDoListRes.rc
//
#define IDR_MANIFEST                    1
#define IDC_CLEARFILTER                 3
#define IDS_FIND_TITLE                  56
#define IDS_REPLACE_TITLE               57
#define IDD_ABOUTBOX                    100
#define IDC_TODOLIST                    101
#define IDD_TODOLIST_DIALOG             102
#define IDC_TRAYICON                    102
#define ID_DEBUGQUERYENDSESSION         104
#define ID_SEARCHLIST                   105
#define IDC_QUICKFIND                   106
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR                     129
#define IDS_SAMPLETASK                  129
#define IDD_RECURRING_TASK_DIALOG       129
#define IDR_TOOLBAR_ORG                 130
#define IDR_TOOLBAR1                    130
#define IDS_BACKUPFILEFOUND             130
#define IDB_TODO2                       131
#define IDD_REC_TASK_DAILY_PAGE         131
#define IDS_SAMPLETEXT                  131
#define IDD_TODOCTRL_DUMMY              132
#define IDB_TODO1                       132
#define IDB_TODO                        132
#define IDD_REC_TASK_WEEKLY_PAGE        132
#define IDD_REC_TASK_MONTHLY_PAGE       133
#define IDD_REC_TASK_YEARLY_PAGE        134
#define IDR_MISC                        135
#define IDB_SIZEGRIP                    136
#define IDD_PREFERENCES_DIALOG          137
#define IDD_PREFTASK_PAGE               138
#define IDD_PREFGEN_PAGE                139
#define IDD_PREFTOOLS_PAGE              140
#define IDR_PLACEHOLDERS                140
#define IDD_PREFUI_PAGE                 141
#define IDB_SOURCECONTROL               141
#define IDD_PREFSHORTCUTS_PAGE          142
#define IDD_PREFFILE_PAGE               143
#define IDD_EXPORT_DIALOG               144
#define IDI_RESIZE                      145
#define IDD_FIND_DIALOG                 146
#define IDD_PREFERENCES                 148
#define IDD_PREFUITASKLIST_PAGE         149
#define IDD_WELCOME_DIALOG              150
#define IDD_WELCOME_PAGE1               150
#define IDD_FINDTEXT_PAGE               152
#define IDD_FINDDATE_PAGE               153
#define IDD_FINDNUM_PAGE                154
#define IDD_PASSWORD_DIALOG             155
#define IDD_PREFTASKDEF_PAGE            156
#define IDD_PREFUITASKLISTCOLORS_PAGE   157
#define IDD_PREFEXPORT_PAGE             158
#define IDR_FINDDLG                     159
#define IDR_TOOLBAR_NEW                 160
#define IDB_TOOLBAR16                   164
#define IDB_TOOLBAR24                   165
#define IDB_FIND16                      166
#define IDB_FIND24                      167
#define IDI_MAINFRAMEXP                 170
#define IDI_MAINFRAME                   171
#define IDI_TRAYICON                    172
#define IDI_TRAYICONTRACK               173
#define IDI_TRAYICONXPTRACK             174
#define IDB_XPCLOSE                     175
#define IDD_DIALOG1                     179
#define IDD_PREFMULTIUSER_PAGE          180
#define IDD_FINDBLANK_PAGE              181
#define IDD_PRINT_DIALOG                182
#define IDD_TASKSELECTION_DIALOG        183
#define IDD_FILTER_DIALOG               186
#define IDD_TRANSFORM_DIALOG            187
#define IDD_OFFSETDATES_DIALOG          188
#define IDD_FINDPRIORITY_PAGE           189
#define IDD_FINDRISK_PAGE               190
#define IDB_TOOLBAR16GRAY               191
#define IDD_FILTER_BAR                  192
#define IDD_TODOLIST_DIALOG1            193
#define IDD_FINDCATEGORY_PAGE           194
#define IDI_TRAYICONXP                  196
#define IDB_LICENSE                     197
#define IDD_KEYBOARDSHORTCUTDISPLAYDIALOG 199
#define IDD_COLUMNSELECTION_DIALOG      201
#define IDD_FINDITEMS_PAGE              202
#define IDD_REGMIGRATION_DIALOG         203
#define IDD_SENDTASKS_DIALOG            204
#define IDR_TREEDRAGDROP                206
#define IDD_IMPORT_DIALOG               207
#define IDD_FINDTASKS_DIALOG            208
#define IDD_WELCOME_PAGE2               209
#define IDD_WELCOME_PAGE3               210
#define IDI_FIND                        211
#define IDB_TREELIST                    212
#define IDB_TASKICONS                   214
#define IDB_TOOLBAR16_NEW               215
#define IDD_TASKICON_DIALOG             216
#define IDD_SETREMINDER_DIALOG          217
#define IDD_SHOWREMINDER_DIALOG         218
#define IDD_REUSERECURRINGTASK_DIALOG   220
#define IDI_VISTASHIELD                 221
#define IDD_MULTISORT_DIALOG            222
#define IDD_PREFFILE2_PAGE              223
#define IDD_PREFTASKCALC_PAGE           224
#define IDD_ADDLOGGEDTIME_DIALOG        225
#define IDD_CSVIMPORTEXPORT_DIALOG      226
#define IDC_TB_FRAME                    1001
#define IDC_REGULARITY                  1001
#define IDC_REC_OPTIONS_FRAME           1002
#define IDC_FILENAME                    1003
#define IDC_DAYS                        1003
#define IDC_RESIZE                      1004
#define IDC_RESIZE2                     1004
#define IDC_WEEKS                       1004
#define IDC_TODOFRAME                   1005
#define IDC_TREE1                       1006
#define IDC_MONTHS                      1006
#define IDC_EDIT1                       1007
#define IDC_DUETASKSTYLESHEET           1007
#define IDC_BY                          1007
#define IDC_PRINTTITLE                  1007
#define IDC_CHARSET                     1007
#define IDC_MONTHDAY                    1007
#define IDC_FROMFILEPATH                1007
#define IDC_SAMPLETASKLIST              1007
#define IDC_COLWIDTHS                   1007
#define IDC_UITHEMEFILE                 1007
#define IDC_PLAYSOUND                   1007
#define IDC_TITLEFILTERTEXT             1007
#define IDC_LOGGEDTIME                  1007
#define IDC_CSVDELIMITER                1007
#define IDC_DONE                        1008
#define IDC_SAVEEXPORTSTYLESHEET        1008
#define IDC_MONTHLIST                   1008
#define IDC_FROMCLIPBOARDTEXT           1008
#define IDC_DATETIMEPICKER1             1009
#define IDC_BEFOREDATE                  1009
#define IDC_PRINTSTYLESHEET             1009
#define IDC_YEARMONTHDAY                1009
#define IDC_ABSOLUTEDATE                1009
#define IDC_AFTERDATE                   1010
#define IDC_THISDATE                    1011
#define IDC_WEEKDAYS                    1011
#define IDC_ENDDATE                     1012
#define IDC_BEGINDATE                   1013
#define IDC_PERSON                      1016
#define IDC_PERSONLABEL                 1022
#define IDC_DEFAULTPERSON               1023
#define IDC_DEFAULTALLOCTO              1023
#define IDC_DEFAULTPRIORITY             1024
#define IDC_CHECK1                      1025
#define IDC_COLORTEXTBYPRIORITY         1025
#define IDC_AUTOHTMLEXPORT              1025
#define IDC_INCLUDECMDLINEPATH          1025
#define IDC_TOGGLETRAYVISIBILITY        1025
#define IDC_RUNMINIMIZED                1025
#define IDC_EXPORTONEFILE               1025
#define IDC_SEARCHTITLE                 1025
#define IDC_AUTOHIDETABBAR              1025
#define IDC_SHOWPARENTSASFOLDERS        1025
#define IDC_FORMATXML                   1025
#define IDC_DEFAULTRISK                 1025
#define IDC_INCLUDESUBTASKS             1025
#define IDC_OFFSETSTARTDATE             1025
#define IDC_LOGTIME                     1025
#define IDC_PRINTDATE                   1025
#define IDC_SEARCHRESULTS               1025
#define IDC_ALLCATEGORIES               1025
#define IDC_USE3RDPARTYSOURCECTRL       1025
#define IDC_ASCENDING                   1025
#define IDC_ASCENDING1                  1025
#define IDC_AUTOEXPORT                  1025
#define IDC_EXPORTTASKIDS               1025
#define IDC_ADDTIMETOTIMESPENT          1025
#define IDC_SHOWCMDIDS                  1025
#define IDC_PREVIEWSAVEAS               1026
#define IDC_DEFAULTTIMEEST              1026
#define IDC_SEARCHCOMMENTS              1026
#define IDC_CHECK3                      1026
#define IDC_STACKTABBARITEMS            1026
#define IDC_COLORTASKBKGND              1026
#define IDC_LIMITINFOTIPCOMMENTS        1026
#define IDC_PREVIEWEXPORT               1026
#define IDC_USESTYLESHEETFORDUEITEMS    1026
#define IDC_ADDFILESTOMRU               1026
#define IDC_OFFSETDUEDATE               1026
#define IDC_LOGTASKSEPARATELY           1026
#define IDC_ALLALLOCTO                  1026
#define IDC_ASCENDING2                  1026
#define IDC_EXPORTFILTERED              1026
#define IDC_INCLUDEUSERINCHECKOUT       1026
#define IDC_ALWAYSONTOP                 1027
#define IDC_USEEARLIESTDUEDATE          1027
#define IDC_SEARCHPERSON                1027
#define IDC_USESTYLESHEETFORSAVE        1027
#define IDC_SORTVISIBLEONLY             1027
#define IDC_DEFAULTCREATEDBY            1027
#define IDC_OFFSETDONEDATE              1027
#define IDC_ASCENDING3                  1027
#define IDC_FONTLIST                    1028
#define IDC_HTMLFONTLIST                1028
#define IDC_DEFAULTALLOCBY              1028
#define IDC_USEHIGHESTPRIORITY          1028
#define IDC_USESTYLESHEETFORPRINT       1028
#define IDC_ROUNDTIMEFRACTIONS          1028
#define IDC_TABWIDTHS                   1029
#define IDC_APPICON                     1029
#define IDC_FONTSIZE                    1029
#define IDC_TREEFONTSIZE                1029
#define IDC_DEFAULTSTATUS               1029
#define IDC_DUEHAVEHIGHESTPRIORITY      1029
#define IDC_APPNAME                     1030
#define IDC_USESYSTRAY                  1030
#define IDC_HTMLFONTSIZE                1030
#define IDC_DEFAULTCATEGORY             1030
#define IDC_COMMENTSFONTSIZE            1030
#define IDC_APPDESCRIPTION              1031
#define IDC_SHOWINFOTIPS                1031
#define IDC_DEFAULTCOST                 1031
#define IDC_NUMLINESPACE                1031
#define IDC_DONEHAVELOWESTPRIORITY      1031
#define IDC_COPYRIGHT                   1032
#define IDC_PRIORITYCOLORS              1032
#define IDC_DEFAULTTIMESPENT            1032
#define IDC_DIVIDER                     1033
#define IDC_HDIVIDER                    1033
#define IDC_CATEGORYCOLORS              1033
#define IDC_SHOWCOMMENTS                1034
#define IDC_HDIVIDER2                   1034
#define IDC_SHOWPERCENTCOLUMN           1035
#define IDC_SHOWPRIORITYCOLUMN          1036
#define IDC_GRAYOUTSUBCOMPLETED         1037
#define IDC_AUTOSAVE                    1038
#define IDC_CONFIRMDELETE               1039
#define IDC_AUTOSAVEONSWITCHTASKLIST    1039
#define IDC_HIDEPERCENTSUBCOMPLETED     1040
#define IDC_AUTOSAVEONSWITCHAPP         1040
#define IDC_TASKNOTIFICATIONS           1041
#define IDC_HIDEUNDEFINEDTIMEST         1041
#define IDC_NOTIFYDUEONLOAD             1041
#define IDC_COLORPRIORITY               1042
#define IDC_NOTIFYREADONLY              1042
#define IDC_HIDEDUETIME                 1042
#define IDC_AUTOARCHIVE                 1043
#define IDC_HIDESTARTTIME               1043
#define IDC_CONFIRMSAVEONEXIT           1044
#define IDC_NOTIFYDUEONSWITCH           1044
#define IDC_HIDEDONETIME                1044
#define IDC_AVERAGEPERCENTSUBCOMPLETION 1045
#define IDC_INCLUDEDONEINAVERAGECALC    1046
#define IDC_SHOWTIMECOLUMN              1047
#define IDC_INCLUDEDONEINPRIORITYCALC   1047
#define IDC_AUTORESORT                  1048
#define IDC_AUTOREFILTER                1049
#define IDC_REMOVEARCHIVEDITEMS         1051
#define IDC_REMOVEONLYONABSCOMPLETION   1052
#define IDC_VARYCOMMENTSHEIGHT          1053
#define IDC_SHOWBUTTONSINTREE           1054
#define IDC_RADIO1                      1055
#define IDC_GRADIENTPRIORITYCOLORS      1055
#define IDC_BEFORE                      1055
#define IDC_MORETHAN                    1055
#define IDC_ALLTASKS                    1055
#define IDC_TABTEXTINDENT               1055
#define IDC_ALLTASKLISTS                1055
#define IDC_SENDACTIVETASKLIST          1055
#define IDC_DAILY                       1055
#define IDC_FROMFILE                    1055
#define IDC_SHARE                       1055
#define IDC_ALLOPTIONS                  1055
#define IDC_REUSETASK                   1055
#define IDC_HTMLEXPORT                  1055
#define IDC_ABSOLUTE                    1055
#define IDC_REMAININGTIMEISDUEDATE      1055
#define IDC_BUTTON1                     1056
#define IDC_LOWPRIORITYCOLOR            1056
#define IDC_ASSIGNSHORTCUT              1056
#define IDC_HELP2                       1056
#define IDC_AFTER                       1056
#define IDC_LESSTHAN                    1056
#define IDC_SELECTALL                   1056
#define IDC_TESTTOOL                    1056
#define IDC_CLEARMRU                    1056
#define IDC_SPACETEXTINDENT             1056
#define IDC_COPYSHORTCUTS               1056
#define IDC_CLEARALLCOLS                1056
#define IDC_SENDSELECTEDTASKS           1056
#define IDC_WEEKLY                      1056
#define IDC_FROMCLIPBOARD               1056
#define IDC_NOSHARE                     1056
#define IDC_HIDEATTRIB                  1056
#define IDC_REMAININGTIMEISSPENT        1056
#define IDC_BUTTON2                     1057
#define IDC_HIGHPRIORITYCOLOR           1057
#define IDC_DELETETOOL                  1057
#define IDC_BETWEEN                     1057
#define IDC_SELECTALLCOLS               1057
#define IDC_MONTHLY                     1057
#define IDC_APPLY                       1057
#define IDC_REMAININGTIMEISPERCENT      1057
#define IDC_APPLYASFILTER               1057
#define IDC_RADIO2                      1058
#define IDC_INDIVIDUALPRIORITYCOLORS    1058
#define IDC_SELTASK                     1058
#define IDC_THIS                        1058
#define IDC_ACTIVETASKLIST              1058
#define IDC_YEARLY                      1058
#define IDC_TONEWTASKLIST               1058
#define IDC_REGISTRY                    1058
#define IDC_NOSAMPLE                    1058
#define IDC_CREATETASK                  1058
#define IDC_OTHEREXPORT                 1058
#define IDC_RELATIVE                    1058
#define IDC_BUTTON3                     1059
#define IDC_SETPRIORITYCOLOR            1059
#define IDC_IMPORT                      1059
#define IDC_TOACTIVETASLIST             1059
#define IDC_INIFILE                     1059
#define IDC_SAMPLE                      1059
#define IDC_TABCONTROL                  1060
#define IDC_SETDEFAULTCOLOR             1060
#define IDC_SETGRIDLINECOLOR            1060
#define IDC_TOSELECTEDTASK              1060
#define IDC_CHECK2                      1061
#define IDC_USEPARENTATTRIB             1061
#define IDC_SPECIFYTREEFONT             1061
#define IDC_ENABLESOURCECONTROL         1061
#define IDC_EXPORTTOFOLDER              1061
#define IDC_MATCHCASE                   1061
#define IDC_AUTOCALCTIMEEST             1061
#define IDC_RIGHTALIGNLABELS            1061
#define IDC_AUTOSELECTSINGLES           1061
#define IDC_DISPLAYFIRSTCOMMENTLINE     1061
#define IDC_SPECIFYGLOBALHOTKEY         1061
#define IDC_OFFSETSUBTASKS              1061
#define IDC_EDIT2                       1062
#define IDC_SHOWMENUBAR                 1062
#define IDC_EXPORTPATH                  1062
#define IDC_SETDONECOLOR                1062
#define IDC_MATCHWHOLEWORD              1062
#define IDC_AUTOCALCPERCENTDONE         1062
#define IDC_DUETASKPERSON               1062
#define IDC_CSVFILEPATH                 1062
#define IDC_CHECKBOXMASKCOLOR           1063
#define IDC_SETCATEGORYCOLOR            1063
#define IDC_MATCHALLWORDS               1063
#define IDC_USEPARENTPERSONATTRIB       1064
#define IDC_USEPARENTALLOCTOATTRIB      1064
#define IDC_HIDEPRIORITYNUMBER          1064
#define IDC_USEPARENTPRIORITYATTRIB     1065
#define IDC_PROMPTRELOADONCHANGE        1065
#define IDC_SETALTLINECOLOR             1065
#define IDC_USEPARENTTIMEESTATTRIB      1066
#define IDC_PROMPTRELOADONWRITABLE      1066
#define IDC_TOOLLIST                    1066
#define IDC_SPECIFYCOMMENTSFONT         1066
#define IDC_USEPARENTCOLORATTRIB        1067
#define IDC_NEWTOOL                     1067
#define IDC_SETDUETASKCOLOR             1067
#define IDC_TOOLPATH                    1068
#define IDC_SETDUETODAYTASKCOLOR        1068
#define IDC_COLUMNVISIBILITY            1069
#define IDC_SETFLAGGEDCOLOR             1069
#define IDC_FONTSIZELABEL               1070
#define IDC_TREEFONTSIZELABEL           1070
#define IDC_HORZDIVIDER                 1071
#define IDC_HORZDIVIDERBOTTOM           1071
#define IDC_COMMENTSFONTSIZELABEL       1071
#define IDC_EXPORTVISIBLEONLY           1072
#define IDC_HORZDIVIDERTOP              1072
#define IDC_EXPORTINCOMPLETEONLY        1073
#define IDC_CMDLINE                     1074
#define IDC_SHOWONSTARTUP               1075
#define IDC_ICONPATH                    1075
#define IDC_USEPERCENTDONEINTIMEEST     1076
#define IDC_DISPLAYPLACEHOLDERS         1077
#define IDC_SHOWCTRLSASCOLUMNS          1078
#define IDC_SHOWCOMMENTSALWAYS          1079
#define IDC_SHOWEDITMENUASCOLUMNS       1080
#define IDC_HOTKEY1                     1081
#define IDC_GLOBALHOTKEY                1081
#define IDC_NEWHOTKEY                   1082
#define IDC_CURHOTKEY                   1083
#define IDC_COMMANDS                    1084
#define IDC_INUSE                       1085
#define IDC_AUTOREPOSCTRLS              1087
#define IDC_CURLABEL                    1088
#define IDC_NEWLABEL                    1089
#define IDC_AUTOSAVEONSYSTRAY           1091
#define IDC_AUTOSAVEFREQUENCY           1092
#define IDC_SYSTRAYOPTION               1093
#define IDC_USECREATIONFORDEFSTARTDATE  1095
#define IDC_TREATSUBCOMPLETEDASDONE     1096
#define IDC_HIDESTARTDUEFORDONETASKS    1097
#define IDC_HIDEPERCENTFORDONETASKS     1098
#define IDC_SHOWPERCENTPROGRESSBAR      1099
#define IDC_SPECIFYGRIDLINECOLOR        1100
#define IDC_AUTOCHECKOUT                1101
#define IDC_SPECIFYDONECOLOR            1101
#define IDC_CHECKOUTONCHECKIN           1102
#define IDC_ALTERNATELINECOLOR          1102
#define IDC_SOURCECONTROLLANONLY        1103
#define IDC_DUETASKCOLOR                1103
#define IDC_READONLYRELOADOPTION        1104
#define IDC_DUETODAYTASKCOLOR           1104
#define IDC_TIMESTAMPRELOADOPTION       1105
#define IDC_COMBO1                      1105
#define IDC_NOTIFYDUEBY                 1105
#define IDC_PREFCHOICE                  1105
#define IDC_FINDOPTION                  1105
#define IDC_NOTIFYDUEBYONLOAD           1105
#define IDC_NEWTASKPOSITION             1105
#define IDC_HOURSINONEDAY               1105
#define IDC_FILTERCOMBO                 1105
#define IDC_CATEGORYLIST                1105
#define IDC_DIRECTION                   1105
#define IDC_RECALCFROM                  1105
#define IDC_SELTASKSSENDAS              1105
#define IDC_ATTRIBCOMBO                 1105
#define IDC_SEARCHLIST                  1105
#define IDC_LEADIN                      1105
#define IDC_SNOOZE                      1105
#define IDC_SPECIFYFLAGGEDCOLOR         1105
#define IDC_SORTBY1                     1105
#define IDC_RECURRINGOPTIONS            1105
#define IDC_RELATIVELEADIN              1105
#define IDC_EXPORTFOLDER                1106
#define IDC_NEWSUBTASKPOSITION          1106
#define IDC_DAYSINONEWEEK               1106
#define IDC_STATUSLIST                  1106
#define IDC_BYUNITS                     1106
#define IDC_OPERATORCOMBO               1106
#define IDC_FILTEROPTIONS               1106
#define IDC_SORTBY2                     1106
#define IDC_QUERYAPPLYCHANGESTOSUBTASKS 1107
#define IDC_NOTIFYDUEBYONSWITCH         1107
#define IDC_COMMENTSFORMAT              1107
#define IDC_ALLOCTOLIST                 1107
#define IDC_SORTBY3                     1107
#define IDC_ALLOCBYLIST                 1108
#define IDC_TASKLISTOPTIONS             1114
#define IDC_FORMATOPTIONS               1115
#define IDC_TREEFONTLIST                1117
#define IDC_INCLUDEDONE                 1118
#define IDC_COMMENTSFONTLIST            1118
#define IDC_INCLUDENOTDONE              1119
#define IDC_RESULTS                     1119
#define IDC_LOOKFOR                     1121
#define IDC_FIND                        1122
#define IDC_RESULTSLABEL                1123
#define IDC_DISPLAYPATHINHEADER         1124
#define IDC_STRIKETHROUGHDONE           1125
#define IDC_GRIPPER                     1126
#define IDC_FULLROWSELECTION            1127
#define IDC_TREECHECKBOXES              1128
#define IDC_SPECIFYTOOLBARIMAGE         1129
#define IDC_TREETASKICONS               1129
#define IDC_TOOLBARIMAGEPATH            1130
#define IDC_SPECIFYCHECKIMAGE           1131
#define IDC_ENABLEHEADERSORTING         1132
#define IDC_MULTIINSTANCE               1133
#define IDC_CHECKBOXIMAGEPATH           1133
#define IDC_SHAREDCOMMENTSHEIGHT        1134
#define IDC_HOSTFRAME                   1135
#define IDC_PAGES                       1136
#define IDC_CHECKINONCLOSE              1137
#define IDC_CHECKINONNOEDIT             1138
#define IDC_TEXT                        1141
#define IDC_PAGEHOST                    1142
#define IDC_MORETHANNUMBER              1143
#define IDC_LESSTHANNUMBER              1144
#define IDC_PASSWORD                    1144
#define IDC_NUMBERSTART                 1145
#define IDC_COMMENTSUSETREEFONT         1145
#define IDC_NUMBEREND                   1146
#define IDC_CONFIRMATION                1146
#define IDC_USEISODATEFORMAT            1147
#define IDC_THISNUMBER                  1147
#define IDC_USEHLSGRADIENT              1148
#define IDC_DEFAULTATTRIBUTES           1149
#define IDC_SHOWWEEKDAYINDATES          1149
#define IDC_INHERITATTRIBUTES           1149
#define IDC_SHOWNONFILEREFSASTEXT       1150
#define IDC_WEIGHTPERCENTCALCBYTIMEEST  1151
#define IDC_WEIGHTPERCENTCALCBYPRIORITY 1152
#define IDC_EXPORTPARENTTITLECOMMENTSONLY 1152
#define IDC_EXPORTSPACEFORNOTES         1153
#define IDC_WEIGHTPERCENTCALCBYNUMSUB   1153
#define IDC_FOCUSTREEONENTER            1154
#define IDC_DISPLAYDUETASKSINHTML       1157
#define IDC_TRACKSELECTEDTASKONLY       1158
#define IDC_DISPLAYDUETASKTITLESONLY    1158
#define IDC_TRACKNONSELECTEDTASKS       1158
#define IDC_TOOLBAR                     1159
#define IDC_TRACKACTIVETASKLISTONLY     1159
#define IDC_TRACKNONACTIVETASKLISTS     1159
#define IDC_REFRESHFINDTASKS            1160
#define IDC_VDIVIDER                    1160
#define IDC_PAUSETIMETRACKINGONSCRNSAVER 1161
#define IDC_TRACKNOSCRNSAVER            1161
#define IDC_TRACKSCREENSAVER            1161
#define IDC_LARGETOOLBARICONS           1162
#define IDC_TRACKHIBERNATED             1162
#define IDC_REMOTEFILECHECK             1164
#define IDC_USEHMSTIMEFORMAT            1165
#define IDC_COLORTEXTBYCATEGORY         1166
#define IDC_COLORTASKSBYCOLOR           1168
#define IDC_SORTDONETASKSATBOTTOM       1168
#define IDC_PATHLABEL                   1169
#define IDC_NOCOLORTASKS                1169
#define IDC_INFOTIPCOMMENTSMAX          1170
#define IDC_KEEPTABSORDERED             1171
#define IDC_SHOWTASKLISTCLOSEBTN        1172
#define IDC_ENABLECTRLMBTNCLOSE         1173
#define IDC_NOCHANGETIME                1174
#define IDC_ONLYSHOWDUETASKFORPERSON    1175
#define IDC_ENABLETDLEXTENSION          1176
#define IDC_RTLCOMMENTS                 1177
#define IDC_ENABLETDLPROTOCOL           1177
#define IDC_RICHEDIT1                   1178
#define IDC_FILTERLABEL                 1179
#define IDC_ALLOCTOFILTERLABEL          1180
#define IDC_ALLOCTOFILTERCOMBO          1181
#define IDC_AUTOFOCUSTASKLIST           1182
#define IDC_PRIORITYFILTERLABEL         1182
#define IDC_COMMENTPOS                  1183
#define IDC_PRIORITYFILTERCOMBO         1183
#define IDC_DEFALLOCTO                  1184
#define IDC_CATEGORYFILTERLABEL         1184
#define IDC_CATEGORYFILTERCOMBO         1185
#define IDC_FRAME                       1185
#define IDC_LOADGROUP                   1185
#define IDC_ARCHIVEGROUP                1186
#define IDC_ALLOCBYFILTERLABEL          1186
#define IDC_SWITCHGROUP                 1187
#define IDC_ALLOCBYFILTERCOMBO          1187
#define IDC_DUEGROUP                    1188
#define IDC_STATUSFILTERLABEL           1188
#define IDC_SAVEGROUP                   1189
#define IDC_STATUSFILTERCOMBO           1189
#define IDC_PRINTGROUP                  1190
#define IDC_RISKFILTERLABEL             1190
#define IDC_TRACKGROUP                  1191
#define IDC_RISKFILTERCOMBO             1191
#define IDC_TIMEGROUP                   1192
#define IDC_OPTIONFILTERLABEL           1192
#define IDC_DEFGROUP                    1193
#define IDC_OPTIONFILTERCOMBO           1193
#define IDC_TOOLBARGROUP                1194
#define IDC_INHERITGROUP                1194
#define IDC_VERSIONFILTERLABEL          1194
#define IDC_SORTGROUP                   1195
#define IDC_DROPLISTGROUP               1195
#define IDC_VERSIONFILTERCOMBO          1195
#define IDC_TABBARGROUP                 1196
#define IDC_COMMENTSGROUP               1197
#define IDC_COLUMNGROUP                 1198
#define IDC_FILTERGROUP                 1198
#define IDC_EXPORTGROUP                 1199
#define IDC_USESTYLESHEET               1201
#define IDC_STYLESHEET                  1202
#define IDC_WARNADDDELARCHIVE           1202
#define IDC_PRIORITYEND                 1204
#define IDC_PRIORITYSTART               1205
#define IDC_LESSTHANPRIORITY            1206
#define IDC_MORETHANPRIORITY            1207
#define IDC_THISPRIORITY                1208
#define IDC_THISRISK                    1209
#define IDC_MORETHANRISK                1210
#define IDC_RISKSTART                   1212
#define IDC_LESSTHANRISK                1213
#define IDC_RISKEND                     1214
#define IDC_EXCLUSIVETRACKING           1216
#define IDC_DEFLISTLABEL                1217
#define IDC_SHOWSUBTASKCOMPLETION       1218
#define IDC_TRANSFORMTITLE              1219
#define IDC_TRANSFORMDATE               1220
#define IDC_ALLOWPARENTRACKING          1221
#define IDC_DONTAUTOSAVEUNSAVED         1222
#define IDC_MULTISELCATFILTER           1223
#define IDC_MULTISELFILTER              1223
#define IDC_CATEGORIES                  1224
#define IDC_MULTISELALLOCTOFILTER       1224
#define IDC_MATCHALLCATEGORIES          1225
#define IDC_DONTREMOVEFLAGGED           1226
#define IDC_RESTORETASKLISTFILTERS      1227
#define IDC_CHECKFORUPDATES             1228
#define IDC_AUTOUPDATEDEPENDEES         1229
#define IDC_SHORTCUTS                   1231
#define IDC_ESCAPEMINIMIZES             1232
#define IDC_EXPANDTASKS                 1233
#define IDC_RECALCFROMLABEL             1234
#define IDC_CHECKFORCHANGESBEFOESAVING  1235
#define IDC_COLUMNS                     1236
#define IDC_MATCHALLITEMS               1237
#define IDC_ITEMS                       1238
#define IDC_ANIMATION                   1239
#define IDC_ENABLEDELAYEDLOADING        1240
#define IDC_RIGHTSIDECOLUMNS            1241
#define IDC_ONCE                        1242
#define IDC_BACKUPONSAVE                1244
#define IDC_BACKUPLOCATION              1245
#define IDC_BACKUPLOCATIONLABEL         1246
#define IDC_NUMBACKUPSTOKEEP            1248
#define IDC_ALLATTRIB                   1249
#define IDC_VISIBLEATTRIB               1250
#define IDC_CUSTOMATTRIB                1251
#define IDC_CUSTOMATTRIBLIST            1252
#define IDC_BACKUPCOUNTLABEL            1253
#define IDC_BACKUPCOUNTTRAIL            1254
#define IDC_FINDLIST                    1285
#define IDC_INSERT                      1286
#define IDC_MOVEUP                      1287
#define IDC_TASKCOLOURGROUP             1289
#define IDC_TEXTINDENTTRAIL             1290
#define IDC_NUMLINESPACETRAIL           1291
#define IDC_COLUMNLIST                  1294
#define IDC_DATETIMEGROUP               1297
#define IDC_INCLUDE                     1298
#define IDC_ICONLIST                    1299
#define IDC_FROMWHERE                   1300
#define IDC_RELATIVEFROMWHERE           1300
#define IDC_TASKTITLE                   1301
#define IDC_WHENTEXT                    1302
#define IDC_CHECK4                      1303
#define IDSNOOZE                        1304
#define IDGOTOTASK                      1305
#define IDC_DELETE                      1306
#define IDC_LIMITCOLWIDTHS              1306
#define IDC_MOVEDOWN                    1307
#define IDC_SEARCHLABEL                 1307
#define IDC_USEUITHEME                  1309
#define IDC_ENABLELIGHTBOXMGR           1311
#define IDC_VISTASHIELD                 1312
#define IDC_UPDATEINHERITATTRIB         1313
#define IDC_BACKUPGROUP                 1314
#define IDC_OTHEREXPORTERS              1316
#define IDC_NODUEDATEDUETODAY           1317
#define IDC_EDITTASKTEXT_LABEL          1318
#define IDC_REUSEOPTIONS                1319
#define IDC_TITLEFILTERLABEL            1320
#define IDC_ABSOLUTETIME                1321
#define IDC_TASKID                      1323
#define IDC_FILTERTASKS                 1324
#define IDC_COLUMNSETUP                 1326
#define IDC_TOUPDATETASKLIST            1328
#define IDB_TOOLBAR24GRAY               30997
#define ID_NEWITEM                      32771
#define ID_DELETETASK                   32772
#define ID_NEWTASK                      32773
#define ID_BUTTON32774                  32774
#define ID_NEWSUBTASK                   32775
#define ID_DELETEALLTASKS               32776
#define ID_EDITTASK                     32777
#define ID_SAVE                         32778
#define ID_LOAD                         32779
#define ID_NEW                          32780
#define ID_TASKDONE                     32782
#define ID_TASKCOLOR                    32783
#define ID_BOLDTASK                     32787
#define ID_SORT                         32792
#define ID_NEWTASK_ATTOP                32797
#define ID_NEWTASK_ATBOTTOM             32798
#define ID_NEWTASK_AFTERSELECTEDTASK    32799
#define ID_NEWTASK_BEFORESELECTEDTASK   32800
#define ID_NEWSUBTASK_ATTOP             32801
#define ID_NEWSUBTASK_ATBOTTOM          32802
#define ID_EDIT_TASKTEXT                32806
#define ID_EDIT_TASKDONE                32807
#define ID_EDIT_TASKCOLOR               32808
#define ID_MOVETASKUP                   32809
#define ID_MOVETASKDOWN                 32810
#define ID_TRAYICON_CLOSE               32811
#define ID_SAVEAS                       32813
#define ID_SAVE_NORMAL                  32816
#define ID_TRAYICON_SHOW                32818
#define ID_TRAYICON                     32819
#define ID_DELETE                       32820
#define ID_LOAD_NORMAL                  32822
#define ID_ABOUT                        32827
#define ID_PREFERENCES                  32828
#define ID_EDIT_COPYASHTML              32833
#define ID_EDIT_COPYASTEXT              32834
#define ID_MAXTASKLIST                  32836
#define ID_OPEN_RELOAD                  32837
#define ID_FILE                         32841
#define ID_ARCHIVE_COMPLETEDTASKS       32842
#define ID_TOOLS                        32843
#define ID_EXPORT_TOHTML                32844
#define ID_EXPORT_TOPLAINTEXT           32845
#define ID_PRINT                        32847
#define ID_MOVETASK                     32848
#define ID_TDD_MOVETASK                 32848
#define ID_MOVETASKLEFT                 32849
#define ID_MOVETASKRIGHT                32850
#define ID_CLOSE                        32851
#define ID_SAVEALL                      32852
#define ID_CLOSEALL                     32853
#define ID_EXIT                         32854
#define ID_TOOLS_IMPORT                 32855
#define ID_TRAYICON_CREATETASK          32857
#define ID_EDIT_SETPRIORITYNONE         32881
#define ID_EDIT_SETPRIORITY0            32882
#define ID_EDIT_SETPRIORITY1            32883
#define IDS_TDC_EDITPROMPT_VER          32884
#define ID_EDIT_SETPRIORITY2            32884
#define ID_EDIT_SETPRIORITY3            32885
#define ID_EDIT_SETPRIORITY4            32886
#define ID_EDIT_SETPRIORITY5            32887
#define ID_EDIT_SETPRIORITY6            32888
#define ID_EDIT_SETPRIORITY7            32889
#define ID_EDIT_SETPRIORITY8            32890
#define ID_EDIT_SETPRIORITY9            32891
#define ID_EDIT_SETPRIORITY10           32892
#define ID_EDIT_SETFILEREF              32893
#define ID_EDIT_OPENFILEREF             32894
#define ID_TOOLS_USERTOOL1              32895
#define ID_TOOLS_USERTOOL2              32896
#define ID_TOOLS_USERTOOL3              32897
#define ID_TOOLS_USERTOOL4              32898
#define ID_TOOLS_USERTOOL5              32899
#define ID_TOOLS_USERTOOL6              32900
#define ID_TOOLS_USERTOOL7              32901
#define ID_TOOLS_USERTOOL8              32902
#define ID_TOOLS_USERTOOL9              32903
#define ID_TOOLS_USERTOOL10             32904
#define ID_TOOLS_USERTOOL11             32905
#define ID_TOOLS_USERTOOL12             32906
#define ID_TOOLS_USERTOOL13             32907
#define ID_TOOLS_USERTOOL14             32908
#define ID_TOOLS_USERTOOL15             32909
#define ID_TOOLS_USERTOOL16             32910
#define ID_TOOLS_PATHNAME               32911
#define ID_TOOLS_SELTASKEXTID           32912
#define ID_TOOLS_SELTASKTITLE           32913
#define ID_TOOLS_FILETITLE              32914
#define ID_TOOLS_FOLDER                 32915
#define ID_TOOLS_FILENAME               32916
#define ID_TOOLS_SELTASKID              32917
#define ID_TOOLS_USERDATE               32918
#define ID_TOOLS_USERFILEPATH           32919
#define ID_TOOLS_USERFOLDER             32920
#define ID_TOOLS_USERTEXT               32921
#define ID_TOOLS_TODAYSDATE             32922
#define ID_TOOLS_TODOLIST               32923
#define ID_TOOLS_SELTASKCOMMENTS        32924
#define ID_TOOLS_EXPORTTOHTML           32929
#define ID_TOOLS_EXPORTTOPLAINTEXT      32930
#define ID_NEXTTOPLEVELTASK             32932
#define ID_PREVTOPLEVELTASK             32933
#define ID_EDIT_FINDTASKS               32934
#define ID_VIEW_MOVETASKLISTLEFT        32938
#define ID_VIEW_MOVETASKLISTRIGHT       32939
#define ID_INFO                         32940
#define ID_TOOLS_SHOWTASKS_DUETODAY     32941
#define ID_TOOLS_SHOWTASKS_DUETOMORROW  32942
#define ID_TOOLS_SHOWTASKS_DUEENDTHISWEEK 32943
#define ID_TOOLS_SHOWTASKS_DUEENDNEXTWEEK 32944
#define ID_TOOLS_SHOWTASKS_DUEENDTHISMONTH 32945
#define ID_TOOLS_SHOWTASKS_DUEENDNEXTMONTH 32946
#define ID_VIEW_TOOLBARONLY             32947
#define ID_VIEW_TOOLBARANDMENU          32948
#define ID_VIEW_MENUONLY                32949
#define ID_NEWTASK_ATTOPSELECTED        32951
#define ID_NEWTASK_ATBOTTOMSELECTED     32952
#define ID_VIEW_NEXT                    32953
#define ID_EDIT_SPELLCHECKCOMMENTS      32956
#define ID_EDIT_SPELLCHECKTITLE         32957
#define ID_FILE_ENCRYPT                 32958
#define ID_FILE_RESETVERSION            32959
#define ID_TOOLS_SPELLCHECKTASKLIST     32964
#define ID_EDIT_PASTESUB                32965
#define ID_EDIT_PASTEAFTER              32966
#define ID_EDIT_CLOCK_TASK              32967
#define ID_VIEW_PREV_SEL                32968
#define ID_VIEW_NEXT_SEL                32969
#define ID_NEWTASK_SPLITTASKINTO_TWO    32971
#define ID_NEWTASK_SPLITTASKINTO_THREE  32972
#define ID_NEWTASK_SPLITTASKINTO_FOUR   32973
#define ID_NEWTASK_SPLITTASKINTO_FIVE   32974
#define ID_DOCKLEFT                     32978
#define ID_DOCKRIGHT                    32979
#define ID_UNDOCKED                     32980
#define ID_UNDOCK                       32981
#define ID_DOCKBELOW                    32982
#define ID_TOOLS_TOGGLECHECKIN          32983
#define ID_VIEW_EXPANDTASK              32984
#define ID_VIEW_COLLAPSETASK            32985
#define ID_VIEW_EXPANDALL               32986
#define ID_VIEW_COLLAPSEALL             32987
#define ID_TOOLS_USEREXPORT1            32989
#define ID_TOOLS_USEREXPORT2            32990
#define ID_TOOLS_USEREXPORT3            32991
#define ID_TOOLS_USEREXPORT4            32992
#define ID_TOOLS_USEREXPORT5            32993
#define ID_TOOLS_USEREXPORT6            32994
#define ID_TOOLS_USEREXPORT7            32995
#define ID_TOOLS_USEREXPORT8            32996
#define ID_TOOLS_USERIMPORT1            32998
#define ID_TOOLS_USERIMPORT2            32999
#define ID_TOOLS_USERIMPORT3            33000
#define ID_TOOLS_USERIMPORT4            33001
#define ID_TOOLS_USERIMPORT5            33002
#define ID_TOOLS_USERIMPORT6            33003
#define ID_TOOLS_USERIMPORT7            33004
#define ID_TOOLS_USERIMPORT8            33005
#define ID_WINDOW1                      33006
#define ID_WINDOW2                      33007
#define ID_WINDOW3                      33008
#define ID_WINDOW4                      33009
#define ID_WINDOW5                      33010
#define ID_WINDOW6                      33011
#define ID_WINDOW7                      33012
#define ID_WINDOW8                      33013
#define ID_WINDOW9                      33014
#define ID_WINDOW10                     33015
#define ID_WINDOW11                     33016
#define ID_WINDOW12                     33017
#define ID_WINDOW13                     33018
#define ID_WINDOW14                     33019
#define ID_WINDOW15                     33020
#define ID_WINDOW16                     33021
#define ID_TOOLS_TRANSFORM              33024
#define ID_VIEW_SORTTASKLISTTABS        33025
#define ID_EDIT_DECTASKPRIORITY         33026
#define ID_EDIT_INCTASKPRIORITY         33027
#define ID_EDIT_INCTASKPERCENTDONE      33028
#define ID_EDIT_DECTASKPERCENTDONE      33029
#define ID_EDIT_FLAGTASK                33031
#define ID_FILE_OPENARCHIVE             33032
#define ID_VIEW_REFRESHFILTER           33036
#define ID_VIEW_SHOWFILTERBAR           33037
#define ID_VIEW_CLEARFILTER             33038
#define ID_VIEW_TOGGLEFILTER            33039
#define ID_TRAYICON_SHOWDUETASKS        33041
#define ID_VIEW_FILTER                  33042
#define ID_FINDONRESULTS                33044
#define ID_BUTTON33046                  33046
#define ID_TOOLS_EXPORTPREFS            33047
#define ID_TOOLS_IMPORTPREFS            33049
#define ID_TABCTRL_PREFERENCES          33050
#define ID_TASKLIST_SELECTCOLUMNS       33051
#define ID_VIEW_PROJECTNAME             33053
#define ID_EDIT_OFFSETDATES             33054
#define ID_PRINTPREVIEW                 33055
#define ID_SHOWTIMELOGFILE              33057
#define ID_COMMENTS_CUT                 33058
#define ID_COMMENTS_COPY                33059
#define ID_COMMENTS_PASTE               33060
#define ID_COMMENTS_PASTEASREF          33061
#define ID_COMMENTS_DELETE              33062
#define ID_COMMENTS_SELECTALL           33063
#define ID_COMMENTS_OPENURL             33064
#define ID_COMMENTS_FILEBROWSE          33065
#define ID_COMMENTS_DATESTAMP_LOCAL     33066
#define ID_COMMENTS_SPELLCHECK          33067
#define ID_COMMENTS_WORDWRAP            33068
#define ID_COMMENTS_UNDO                33069
#define ID_COMMENTS_REDO                33070
#define ID_COMMENTS_FIND                33071
#define ID_COMMENTS_FINDREPLACE         33072
#define ID_TRAYICON_SHOWDUETASKS1       33073
#define ID_TRAYICON_SHOWDUETASKS2       33074
#define ID_TRAYICON_SHOWDUETASKS3       33075
#define ID_TRAYICON_SHOWDUETASKS4       33076
#define ID_TRAYICON_SHOWDUETASKS5       33077
#define ID_TRAYICON_SHOWDUETASKS6       33078
#define ID_TRAYICON_SHOWDUETASKS7       33079
#define ID_TRAYICON_SHOWDUETASKS8       33080
#define ID_TRAYICON_SHOWDUETASKS9       33081
#define ID_TRAYICON_SHOWDUETASKS10      33082
#define ID_TRAYICON_SHOWDUETASKS11      33083
#define ID_TRAYICON_SHOWDUETASKS12      33084
#define ID_TRAYICON_SHOWDUETASKS13      33085
#define ID_TRAYICON_SHOWDUETASKS14      33086
#define ID_TRAYICON_SHOWDUETASKS15      33087
#define ID_TRAYICON_SHOWDUETASKS16      33088
#define ID_TRAYICON_SHOWDUETASKS17      33089
#define ID_TRAYICON_SHOWDUETASKS18      33090
#define ID_TRAYICON_SHOWDUETASKS19      33091
#define ID_TRAYICON_SHOWDUETASKS20      33092
#define ID_TASKCONTEXT_COPYAS_TASKREF   33093
#define ID_TASKCONTEXT_COPYAS_TASKDEPENDENCY 33094
#define ID_TOOLS_CHECKFORUPDATES        33095
#define ID_VIEW_PREV                    33097
#define ID_TOOLS_CHECKOUT               33098
#define ID_TOOLS_CHECKIN                33099
#define ID_TOOLS_EXPORT                 33100
#define ID_HELP_KEYBOARDSHORTCUTS       33102
#define ID_HELP_FEEDBACKANDSUPPORT      33103
#define ID_HELP_CONTACTUS               33104
#define ID_HELP_ONLINE                  33105
#define ID_HELP_WIKI                    33106
#define ID_HELP_LICENSE                 33107
#define ID_EDIT_INSERTDATETIME          33119
#define ID_SORT_BYCOST                  33120
#define ID_SORT_BYFLAG                  33121
#define ID_SORT_BYDONEDATE              33122
#define ID_SORT_BYPRIORITY              33123
#define ID_SORT_BYCOLOR                 33124
#define ID_SORT_BYPERSON                33125
#define ID_SORT_BYPERCENT               33126
#define ID_SORT_BYSTARTDATE             33127
#define ID_SORT_BYDUEDATE               33128
#define ID_SORT_BYTIMEEST               33129
#define ID_SORT_BYID                    33130
#define ID_SORT_BYNAME                  33131
#define ID_SORT_BYDONE                  33132
#define ID_SORT_BYALLOCBY               33133
#define ID_SORT_BYSTATUS                33134
#define ID_SORT_BYCATEGORY              33135
#define ID_SORT_BYTIMESPENT             33136
#define ID_SORT_BYALLOCTO               33137
#define ID_SORT_BYCREATIONDATE          33138
#define ID_SORT_BYCREATEDBY             33139
#define ID_SORT_BYMODIFYDATE            33140
#define ID_SORT_BYLASTMOD               33141
#define ID_SORT_BYRISK                  33142
#define ID_SORT_BYEXTERNALID            33143
#define ID_SORT_BYVERSION               33144
#define ID_SORT_BYRECURRENCE            33145
#define ID_SORT_BYREMAINING             33146
#define ID_SORT_BYRECENTEDIT            33147
#define ID_SORT_BYICON                  33148
#define ID_SORT_BYTIMETRACKING          33149
#define ID_SORT_BYFILEREF               33150
#define ID_SORT_NONE                    33151
#define ID_SORT_MULTI                   33152
#define ID_HELP_COMMANDLINE             33180
#define ID_HELP_DONATE                  33181
#define ID_EDIT_CLEARTASKCOLOR          33182
#define ID_EDIT_SELECTALL               33183
#define ID_EDIT_COPYASPATH              33185
#define ID_TASKCONTEXT_COPYASDEPENDENCYFULL 33186
#define ID_TASKCONTEXT_COPYASREFFULL    33187
#define ID_EDIT_COPYAS_DEPEND           33188
#define ID_EDIT_COPYAS_DEPENDFULL       33189
#define ID_EDIT_COPYAS_PATH             33190
#define ID_EDIT_COPYAS_REFFULL          33191
#define ID_EDIT_COPYAS_REF              33192
#define ID_EDIT_COPYAS_TEXT             33193
#define ID_EDIT_COPYAS_HTML             33194
#define ID_TOOLS_USEREXT1               33195
#define ID_TOOLS_USEREXT2               33196
#define ID_TOOLS_USEREXT3               33197
#define ID_TOOLS_USEREXT4               33198
#define ID_TOOLS_USEREXT5               33199
#define ID_TOOLS_USEREXT6               33200
#define ID_TOOLS_USEREXT7               33201
#define ID_TOOLS_USEREXT8               33202
#define ID_TOOLS_USEREXT9               33203
#define ID_TOOLS_USEREXT10              33204
#define ID_TOOLS_USEREXT11              33205
#define ID_TOOLS_USEREXT12              33206
#define ID_TOOLS_USEREXT13              33207
#define ID_TOOLS_USEREXT14              33208
#define ID_TOOLS_USEREXT15              33209
#define ID_TOOLS_USEREXT16              33210
#define ID_CLOSEALLBUTTHIS              33211
#define ID_SENDTASKS                    33212
#define ID_EDIT_INSERTDATE              33215
#define ID_TDD_COPYTASK                 33217
#define ID_TDD_TASKDEPENDENCY           33218
#define ID_TDD_ADDTASKDEPENDENCY        33218
#define ID_TDD_TASKREFERENCE            33219
#define ID_NEXTTASK                     33220
#define ID_PREVTASK                     33221
#define ID_FIND_SAVE                    33226
#define ID_FIND_ADDRULE                 33227
#define ID_FIND_DELETERULE              33228
#define ID_FIND_FIND                    33229
#define ID_FIND_NEW                     33230
#define ID_FIND_DELETESEARCH            33231
#define ID_FIND_NEWSEARCH               33232
#define ID_FIND_SAVESEARCH              33233
#define ID_FIND_MOVERULEUP              33235
#define ID_FIND_MOVERULEDOWN            33236
#define ID_MINIMIZETOTRAY               33237
#define ID_TDD_SETTASKDEPENDENCY        33237
#define ID_VIEW_TASKTREE                33238
#define ID_VIEW_TOGGLETREEANDLIST       33238
#define ID_VIEW_TASKLIST                33239
#define ID_VIEW_TOGGLETASKSANDCOMMENTS  33243
#define ID_EDIT_QUICKFIND               33244
#define ID_EDIT_QUICKFINDNEXT           33245
#define ID_EDIT_QUICKFINDPREV           33246
#define ID_LOAD_FROMWEB                 33248
#define ID_SAVE_TOWEB                   33249
#define ID_EDIT_SETTASKICON             33250
#define ID_EDIT_SETREMINDER             33251
#define ID_EDIT_CLEARREMINDER           33252
#define ID_EDIT_CLEARTASKICON           33253
#define ID_TOOLS_REMOVEFROMSOURCECONTROL 33255
#define ID_ARCHIVE_SELECTEDTASKS        33257
#define ID_MAXCOMMENTS                  33258
#define ID_TOOLS_SELTASKALLOCBY         33260
#define ID_TOOLS_SELTASKALLOCTO         33261
#define ID_ADDTIMETOLOGFILE             33263
#define ID_VIEW_TOGGLETASKEXPANDED      33264
#define ID_VIEW_SHOWTASKLISTTABBAR      33265
#define ID_VIEW_SHOWTREELISTTABBAR      33266
#define ID_TOOLS_SELTASKFILELINK        33267
#define ID_SB_SELCOUNT                  33268
#define ID_SB_SELTIMEEST                33269
#define ID_SB_SELTIMESPENT              33270
#define ID_SB_SELCOST                   33271
#define ID_SB_FILEVERSION               33276
#define ID_SB_TASKCOUNT                 33278
#define ID_SB_FILEPATH                  33280
#define ID_SB_SPACER                    33282
#define ID_SB_FOCUS                     33283
#define IDS_COMMENTSTYPE                33284
#define ID_EDIT_INSERTTIME              33284
#define IDS_FOCUS_FILTERBAR             33285
#define IDS_FOCUS_TASKS                 33286
#define IDS_PTP_NEWTOOL                 57671
#define IDS_PTP_TOOLNAME                57672
#define IDS_PTP_TOOLPATH                57673
#define IDS_PTP_ARGUMENTS               57674
#define IDS_TDLBC_DONE                  57675
#define IDS_TDLBC_PRIORITY              57676
#define IDS_TDLBC_ALLOCTO               57677
#define IDS_TDLBC_ALLOCBY               57678
#define IDS_TDLBC_DONEDATE              57679
#define IDS_TDLBC_DUEDATE               57680
#define IDS_TDLBC_STARTDATE             57681
#define IDS_TDLBC_TIMEEST               57682
#define IDS_TDLBC_TIMESPENT             57683
#define IDS_TDLBC_CATEGORY              57684
#define IDS_TDLBC_STATUS                57685
#define IDS_TDLBC_CREATEDATE            57686
#define IDS_TDLBC_CREATEDBY             57687
#define IDS_TDLBC_ID                    57688
#define IDS_TDLBC_POS                   57689
#define IDS_TDLBC_PERCENT               57690
#define IDS_TDLBC_FILEREF               57691
#define IDS_TDLBC_FLAG                  57692
#define IDS_TDLBC_TRACKTIME             57693
#define IDS_PSP_SHORTCUT                57694
#define IDS_PSP_MENUITEM                57695
#define IDS_PSP_CURRENTLYASSIGNED       57696
#define IDS_PTDP_COLOR                  57697
#define IDS_PTDP_NAMEPROMPT             57698
#define IDS_PTDP_STATUSPROMPT           57699
#define IDS_PTDP_CATEGORYPROMPT         57700
#define IDS_PFP_SELECTFOLDER            57701
#define IDS_FTD_RESULTS                 57702
#define IDS_FTD_NORESULTS               57703
#define IDS_FTD_SOMERESULTS             57704
#define IDS_FTD_TITLECOMMENTS           57705
#define IDS_FTD_PRIORITY                57706
#define IDS_FTD_PERCENT                 57707
#define IDS_FTD_TIMEEST                 57708
#define IDS_FTD_TIMESPENT               57709
#define IDS_FTD_STARTDATE               57710
#define IDS_FTD_DUEDATE                 57711
#define IDS_FTD_DONEDATE                57712
#define IDS_FTD_ALLOCTO                 57713
#define IDS_FTD_ALLOCBY                 57714
#define IDS_FTD_STATUS                  57715
#define IDS_FTD_CATEGORY                57716
#define IDS_FTD_ID                      57717
#define IDS_FTD_FLAG                    57718
#define IDS_FTD_CREATEDDATE             57719
#define IDS_FTD_CREATEDATE              57719
#define IDS_FTD_CREATEDBY               57720
#define IDS_ED_NOMAKEEXPORTPATH         57721
#define IDS_ED_NOMAKEEXPORTPATH_TITLE   57722
#define IDS_ED_FOLDER                   57723
#define IDS_ED_FILEPATH                 57724
#define IDS_PREFERENCES_TITLE           57725
#define IDS_PREF_TITLE                  57725
#define IDS_PREF_GEN                    57726
#define IDS_PREF_MULTIUSER              57727
#define IDS_PREF_MULTIUSERSS            57728
#define IDS_PREF_UI                     57729
#define IDS_PREF_UITASK                 57730
#define IDS_PREF_UITASKCOLOR            57731
#define IDS_PREF_TASK                   57732
#define IDS_PREF_TASKDEF                57733
#define IDS_PREF_EXPORT                 57734
#define IDS_PREF_TOOLS                  57735
#define IDS_PREF_SHORTCUT               57736
#define IDS_WELCOME                     57737
#define IDS_PREF_TASKDEFINHERIT         57738
#define IDS_PREF_UIFILTERING            57739
#define IDS_STATUSBAR                   57740
#define IDS_PREF_UITOOLBAR              57740
#define IDS_OPENTASKLIST_TITLE          57741
#define IDS_INVALIDTASKLIST             57742
#define IDS_STATUSREADONLY              57743
#define IDS_STATUSNEWERFORMAT           57744
#define IDS_STATUSCHECKEDOUT            57745
#define IDS_STATUSCHECKEDIN             57746
#define IDS_STATUSSOURCECONTROLLED      57747
#define IDS_SAVETASKLISTAS_TITLE        57748
#define IDS_OPENRECENT_FAILED           57749
#define IDS_OPENREADONLY                57750
#define IDS_OPENSOURCECONTROLLED        57751
#define IDS_OPENNEWER                   57752
#define IDS_DUETOMORROW                 57753
#define IDS_DUETHISWEEK                 57754
#define IDS_DUENEXTWEEK                 57755
#define IDS_DUETHISMONTH                57756
#define IDS_DUENEXTMONTH                57757
#define IDS_DUETASKS_TITLE              57758
#define IDS_ABOUTCOPYRIGHT              57759
#define IDS_ABOUTHEADING                57760
#define IDS_PASTETOPLEVELTASK           57761
#define IDS_CONFIRMRELOAD               57762
#define IDS_PRINTFAILED                 57763
#define IDS_SAVEBEFORECLOSE             57764
#define IDS_TABSWITCHTOOLTIP            57765
#define IDS_MINIMIZETOTRAY              57766
#define IDS_EXITTODOLIST                57767
#define IDS_READONLYTOWRITABLE          57768
#define IDS_WRITABLETOREADONLY          57769
#define IDS_TASKLISTSRELOADED           57770
#define IDS_MODIFIEDELSEWHERE           57771
#define IDS_TASKLISTSCHECKEDOUT         57772
#define IDS_IMPORTTASKLIST_TITLE        57773
#define IDS_SETFILEREF_TITLE            57774
#define IDS_CHECKEDOUTBYOTHER           57775
#define IDS_SAVEBEFORECHECKIN           57776
#define IDS_SELECTSTYLESHEET_TITLE      57777
#define IDS_SAVETRANSFORM_TITLE         57778
#define IDS_DUETODAY                    57779
#define IDS_NODUETODAY                  57780
#define IDS_NODUETOMORROW               57781
#define IDS_NODUETHISWEEK               57782
#define IDS_NODUENEXTWEEK               57783
#define IDS_NODUETHISMONTH              57784
#define IDS_NODUENEXTMONTH              57785
#define IDS_EXPORTTASKLIST_TITLE        57786
#define IDS_NEWTASK_TIP                 57787
#define IDS_NEWSUBTASK_TIP              57788
#define IDS_EDITTASK_TIP                57789
#define IDS_OPENTASKLIST_TIP            57790
#define IDS_DELETETASK_TIP              57791
#define IDS_HELP_TIP                    57792
#define IDS_MAXTASKLIST_TIP             57793
#define IDS_MOVETASKS_DROPTIP           57794
#define IDS_SORTTASKS_DROPTIP           57795
#define IDS_NEWTASK_DROPTIP             57796
#define IDS_EDITTASK_DROPTIP            57797
#define IDS_FILE_DROPTIP                57798
#define IDS_DELETETASKS_DROPTIP         57799
#define IDS_TOOLS_DROPTIP               57800
#define IDS_HELP_DROPTIP                57801
#define IDS_VIEW_DROPTIP                57802
#define IDS_PREFS_TIP                   57803
#define IDS_TDLFILEFILTER               57804
#define IDS_XSLFILEFILTER               57805
#define IDS_TRANSFORMFILEFILTER         57806
#define IDS_ALLFILEFILTER               57807
#define IDS_RECENTFILES                 57808
#define IDS_COPYRIGHT                   57809
#define IDS_SAVETASKLIST_TITLE          57810
#define IDS_SAVEREADONLY                57811
#define IDS_STATUSBARSHORT              57812
#define IDS_PREF_UISORTING              57812
#define IDS_SAVEFAILED                  57813
#define IDS_XMLFILEFILTER               57814
#define IDS_PRINTFAILED_TITLE           57815
#define IDS_WANTRELOAD                  57816
#define IDS_CHECKOUTFAILED              57817
#define IDS_INIFILEFILTER               57818
#define IDS_CONFIRMRELOAD_TITLE         57819
#define IDS_CONFIRMSAVE_TITLE           57820
#define IDS_STATUSCHANGE_TITLE          57821
#define IDS_TIMESTAMPCHANGE_TITLE       57822
#define IDS_CHECKOUT_TITLE              57823
#define IDS_CHECKIN_TITLE               57824
#define IDS_TASK                        57825
#define IDS_EARLIERVERRUNNING           57826
#define IDS_LOCATEHELP                  57827
#define IDS_LOCATEHELP_TITLE            57828
#define IDS_HELPFILEFILTER              57829
#define IDS_COMMENTFORMATCHANGE         57830
#define IDS_COMMENTFORMATCHANGE_TITLE   57831
#define IDS_FD_DOCKLEFT                 57832
#define IDS_POSTEXPORTPREFS             57832
#define IDS_FD_DOCKRIGHT                57833
#define IDS_POSTIMPORTPREFS             57833
#define IDS_FD_DOCKBELOW                57834
#define IDS_PREF_UITABBAR               57834
#define IDS_FD_UNDOCK                   57835
#define IDS_PREF_UICOMMENTS             57835
#define IDS_PTP_PLACEHOLDERS            57836
#define IDS_TH_TESTTOOL                 57837
#define IDS_TH_TESTTOOL_TITLE           57838
#define IDS_SELECTTASKLIST_TITLE        57839
#define IDS_USERDEFINEDTOOLS            57840
#define IDS_PTP_ICONPATH                57841
#define IDS_FINDTASKS_TIP               57842
#define IDS_OPENACCESSDENIED            57843
#define IDS_UNKNOWNOPENERROR            57844
#define IDS_PREF_UITASKCOLUMNS          57845
#define IDS_BADMSXML                    57846
#define IDS_SAVEACCESSDENIED            57847
#define IDS_UNKNOWNSAVEERROR2           57848
#define IDS_TDLBC_MODIFYDATE            57849
#define IDS_TDLBC_RISK                  57850
#define IDS_TDLBC_EXTERNALID            57851
#define IDS_FTD_LASTMOD                 57852
#define IDS_FTD_RISK                    57853
#define IDS_FTD_EXTID                   57854
#define IDS_SOURCECONTROL_TIP           57855
#define IDS_COMMANDLINEOPTIONS          57856
#define IDS_PTDP_DUEDATE                57857
#define IDS_PRINTDLG_PREVIEW_BUTTON     57858
#define IDS_PRINTDLG_PRINT_BUTTON       57859
#define IDS_PRINTDLG_PREVIEW_TITLE      57860
#define IDS_PRINTDLG_PRINT_TITLE        57861
#define IDS_TDC_COLUMN_ID               57862
#define IDS_TDC_COLUMN_PRIORITY         57863
#define IDS_TDC_COLUMN_PERCENT          57864
#define IDS_TDC_COLUMN_TIMEEST          57865
#define IDS_TDC_COLUMN_TIMESPENT        57866
#define IDS_TDC_COLUMN_STARTDATE        57867
#define IDS_TDC_COLUMN_DUEDATE          57868
#define IDS_TDC_COLUMN_DONEDATE         57869
#define IDS_TDC_COLUMN_ALLOCTO          57870
#define IDS_TDC_COLUMN_ALLOCBY          57871
#define IDS_TDC_COLUMN_STATUS           57872
#define IDS_TDC_COLUMN_CATEGORY         57873
#define IDS_TDC_COLUMN_TASK             57874
#define IDS_TDC_COLUMN_CREATEDBY        57875
#define IDS_TDC_COLUMN_CREATEDATE       57876
#define IDS_TDC_COLUMN_MODIFYDATE       57877
#define IDS_TDC_COLUMN_RISK             57878
#define IDS_TDC_COLUMN_EXTID            57879
#define IDS_TDC_SCALE0                  57880
#define IDS_TDC_SCALE1                  57881
#define IDS_TDC_SCALE2                  57882
#define IDS_TDC_SCALE3                  57883
#define IDS_TDC_SCALE4                  57884
#define IDS_TDC_SCALE5                  57885
#define IDS_TDC_SCALE6                  57886
#define IDS_TDC_SCALE7                  57887
#define IDS_TDC_SCALE8                  57888
#define IDS_TDC_SCALE9                  57889
#define IDS_TDC_SCALE10                 57890
#define IDS_TDC_FIELD_TASKLIST          57891
#define IDS_TDC_FIELD_PRIORITY          57892
#define IDS_TDC_FIELD_PERCENT           57893
#define IDS_TDC_FIELD_TIMEEST           57894
#define IDS_TDC_FIELD_TIMESPENT         57895
#define IDS_TDC_FIELD_STARTDATE         57896
#define IDS_TDC_FIELD_DUEDATE           57897
#define IDS_TDC_FIELD_DONEDATE          57898
#define IDS_TDC_FIELD_ALLOCTO           57899
#define IDS_TDC_FIELD_ALLOCBY           57900
#define IDS_TDC_FIELD_STATUS            57901
#define IDS_TDC_FIELD_CATEGORY          57902
#define IDS_TDC_FIELD_FILEREF           57903
#define IDS_TDC_FIELD_COMMENTS          57904
#define IDS_TDC_FIELD_PROJECT           57905
#define IDS_TDC_FIELD_RISK              57906
#define IDS_TDC_FIELD_EXTID             57907
#define IDS_TDCTIP_TASK                 57908
#define IDS_TDCTIP_PRIORITY             57909
#define IDS_TDCTIP_PERCENT              57910
#define IDS_TDCTIP_TIMEEST              57911
#define IDS_TDCTIP_STARTDATE            57912
#define IDS_TDCTIP_DUEDATE              57913
#define IDS_TDCTIP_DONEDATE             57914
#define IDS_TDCTIP_ALLOCTO              57915
#define IDS_TDCTIP_FILEREF              57916
#define IDS_TDCTIP_ALLOCBY              57917
#define IDS_TDCTIP_STATUS               57918
#define IDS_TDCTIP_CATEGORY             57919
#define IDS_TDCTIP_TIMESPENT            57920
#define IDS_TDCTIP_COMMENTS             57921
#define IDS_TDCTIP_LASTMOD              57922
#define IDS_TDCTIP_RISK                 57923
#define IDS_TDCTIP_EXTID                57924
#define IDS_TDC_CONFIRMDELETESEL        57925
#define IDS_TDC_CONFIRMDELETEONEWARNSUBTASKS 57926
#define IDS_TDC_CONFIRMDELETEMOREWARNSUBTASKS 57927
#define IDS_TDC_CONFIRMDELETEALL        57928
#define IDS_TDC_CONFIRMDELETE_TITLE     57929
#define IDS_TDC_CONFIRMADD_TITLE        57930
#define IDS_TDC_CONFIRMRELOAD           57931
#define IDS_TDC_CONFIRMRELOAD_TITLE     57932
#define IDS_TDC_CONFIRMOVERWRITE        57933
#define IDS_TDC_CONFIRMOVERWRITE_TITLE  57934
#define IDS_TDC_SPELLCHECK_TITLE        57935
#define IDS_TDC_NOTITLESPELLERRORS      57936
#define IDS_TDC_NOCOMMENTSPELLERRORS    57937
#define IDS_TDC_TASKIDNOTFOUND          57938
#define IDS_TDC_TASKIDNOTFOUND_TITLE    57939
#define IDS_TDC_ZEROINVALIDTASKID       57940
#define IDS_TDC_ZEROINVALIDTASKID_TITLE 57941
#define IDS_TDC_SEECOMMENTS             57942
#define IDS_TDC_STARTSTOPCLOCK          57943
#define IDS_TDC_SELTASKHASINCOMPLETE    57944
#define IDS_TDC_TASKHASINCOMPLETE       57945
#define IDS_TDC_ARCHIVEPROJECT          57946
#define IDS_TDC_UNTITLEDFILE            57947
#define IDS_TDC_TASK                    57948
#define IDS_TDC_DONE                    57949
#define IDS_TDC_WARNADDTOARCHIVE        57950
#define IDS_TDC_WARNDELETEFROMARCHIVE   57951
#define IDS_TDC_EDITPROMPT_NAME         57952
#define IDS_TDC_EDITPROMPT_COMMENTS     57953
#define IDS_TDC_EDITPROMPT_STATUS       57954
#define IDS_TDC_EDITPROMPT_CATEGORY     57955
#define IDS_TDC_EDITPROMPT_FILEREF      57956
#define IDS_TDC_EDITPROMPT_PROJECT      57957
#define IDS_TDC_EDITPROMPT_EXTID        57958
#define IDS_TDC_TASKLISTPROMPT          57959
#define IDS_TDC_FILTEREDTASKLISTPROMPT  57960
#define IDS_RES_VERSION                 57961
#define IDS_MISMATCHEDRESOURCES         57962
#define IDS_SAVEALL_TIP                 57963
#define IDS_SAVE_TIP                    57964
#define IDS_TDC_FIELD_COST              57965
#define IDS_TDC_COLUMN_COST             57966
#define IDS_TDC_EDITPROMPT_DEPENDS      57967
#define IDS_TDLBC_COST                  57968
#define IDS_FTD_COST                    57969
#define IDS_HOURS_ABBREV                57970
#define IDS_MINS_ABBREV                 57971
#define IDS_MONTHS_ABBREV               57972
#define IDS_WEEKS_ABBREV                57973
#define IDS_YEARS_ABBREV                57974
#define IDS_DAYS_ABBREV                 57975
#define IDS_TDC_EXTIDLINK_TIP           57976
#define IDS_TDC_FIELD_DEPENDENCY        57977
#define IDS_TDC_COLUMN_DEPENDS          57978
#define IDS_TDLBC_DEPENDS               57979
#define IDS_TDC_DEPENDSLINK_TIP         57980
#define IDS_TDC_SELTASKHASDEPENDENCY    57981
#define IDS_TDC_SELTASKSHAVEDEPENDENCIES 57982
#define IDS_TDCTIP_COST                 57983
#define IDS_TDCTIP_DEPENDS              57984
#define IDS_NOENCRYPTIONDLL             57985
#define IDS_UNKNOWNENCRYPTION           57986
#define IDS_ENCRYPTEDFILE               57987
#define IDS_DECRYPTFAILED               57988
#define IDS_PASSWORDTITLE               57989
#define IDS_PD_TITLE                    57989
#define IDS_PASSWORDPROMPT              57990
#define IDS_PD_PASSWORDLABEL            57990
#define IDS_CONFIRMPROMPT               57991
#define IDS_PD_CONFIRMLABEL             57991
#define IDS_CONFIRMFAILED               57992
#define IDS_PD_CONFIRMFAILED            57992
#define IDS_OK                          57993
#define IDS_CANCEL                      57994
#define IDS_ENABLEENCRYPTION            57995
#define IDS_SELECTENCRYPTED             57996
#define IDS_TDC_COLUMN_POS              57997
#define IDS_TDLBC_TITLE                 57998
#define IDS_ED_CONFIRMEXPORTPATHMULTI   57999
#define IDS_ED_CONFIRMEXPORTPATH_TITLE  58000
#define IDS_INVALIDPREFFILE             58001
#define IDS_TDLBC_COMMENTS              58002
#define IDS_BADXML                      58003
#define IDS_TASKLISTNOTFOUND            58004
#define IDS_ED_CONFIRMEXPORTPATH        58005
#define IDS_NOFILTER                    58006
#define IDS_NOCATEGORY                  58007
#define IDS_BADPLUGINVERSIONS           58008
#define IDS_BADPLUGINTITLE              58009
#define IDS_FIXDEPENDEESTITLE           58010
#define IDS_FIXDEPENDEES                58011
#define IDS_LICENSE                     58012
#define IDS_SETFOCUS2TASLIST            58013
#define IDS_SETFOCUS2TASKLIST           58013
#define IDS_NOWUW                       58014
#define IDS_NOALLOCTO                   58015
#define IDS_TDC_FIELD_RECURRENCE        58016
#define IDS_TDC_COLUMN_RECURRENCE       58017
#define IDS_ONCEONLY                    58018
#define IDS_DAILY                       58019
#define IDS_WEEKLY                      58020
#define IDS_MONTHLY                     58021
#define IDS_YEARLY                      58022
#define IDS_TDLBC_RECURRENCE            58023
#define IDS_TDLBC_VERSION               58024
#define IDS_TDC_COLUMN_VERSION          58025
#define IDS_TDC_FIELD_VERSION           58026
#define IDS_TDCTIP_VERSION              58027
#define IDS_TE_RECALCPROMPT             58028
#define IDS_TDC_RECALCPROMPT            58028
#define IDS_TE_RECALCTITLE              58029
#define IDS_TDC_RECALCTITLE             58029
#define IDS_INIHASNOTOOLS               58030
#define IDS_COMMANDLINEOPTIONSTITLE     58031
#define IDS_SB_TREETASKCOUNT_TIP        58043
#define IDS_TDC_NONE                    58047
#define IDS_TDC_ANY                     58048
#define IDS_FTD_VERSION                 58049
#define IDS_TDC_ANYONE                  58050
#define IDS_WARN_CONVERT_INI            58051
#define IDS_TABTIP_READONLY             58052
#define IDS_TABTIP_CHECKEDIN            58053
#define IDS_TABTIP_CHECKEDOUT           58054
#define IDS_TABTIP_NOTLOADED            58055
#define IDS_PREF_TASKTIME               58056
#define IDS_PREF_TASKCALCS              58057
#define IDS_PREF_FILELOAD               58058
#define IDS_PREF_FILEARCHIVE            58059
#define IDS_PREF_FILENOTIFY             58060
#define IDS_PREF_FILESAVE               58061
#define IDS_PREF_MULTIUSERFILE          58062
#define IDS_PREF_FILE                   58063
#define ID_SB_SELCOUNTONE               58064
#define IDS_OPENSHARINGVIOLATION        58065
#define IDS_SAVESHARINGVIOLATION        58066
#define IDS_PSP_RESERVED                58067
#define IDS_RESERVEDSHORTCUT_MSG        58068
#define IDS_RESERVEDSHORTCUT_TITLE      58069
#define IDS_TDC_FIELD_COLOUR            58070
#define IDS_TASKLISTEXTENDEDSELECTION   58071
#define IDS_PEP_RESETCHARSET            58072
#define IDS_COMMENTSGOTOERRMSG          58073
#define IDS_SAVEBADXML                  58074
#define IDS_TDLLINKLOADFAILED           58075
#define IDS_FTD_COMMENTS                58076
#define IDS_FTD_TASKNAME                58077
#define IDS_FP_EQUALS                   58078
#define IDS_FP_NOT_EQUALS               58079
#define IDS_FP_CONTAINS                 58080
#define IDS_FP_INCLUDES                 58080
#define IDS_FP_NOT_CONTAINS             58081
#define IDS_FP_NOT_INCLUDES             58081
#define IDS_FP_GREATER                  58082
#define IDS_FP_LESS                     58083
#define IDS_FP_BEFORE                   58084
#define IDS_FP_AFTER                    58085
#define IDS_FP_GREATER_OR_EQUAL         58086
#define IDS_FP_LESS_OR_EQUAL            58087
#define IDS_FP_ON_OR_BEFORE             58088
#define IDS_FP_ON_OR_AFTER              58089
#define IDS_FP_SET                      58090
#define IDS_FP_NOT_SET                  58091
#define IDS_FP_NEW_RULE                 58092
#define IDS_FP_AND                      58093
#define IDS_FP_OR                       58094
#define IDS_TDC_SELTASKHASCIRCULARDEPENDENCY 58095
#define IDS_TDC_SELTASKSHAVECIRCULARDEPENDENCIES 58096
#define IDS_TDC_FIELD_DUETIME           58097
#define IDS_TASKTREE                    58098
#define IDS_LISTVIEW                    58099
#define IDS_FT_TASK                     58100
#define IDS_FT_WHATMATCHED              58101
#define IDS_TDLBC_TITLEORCOMMENTS       58102
#define IDS_TDLBC_ANYTEXTATTRIB         58103
#define IDS_FT_ATTRIB                   58104
#define IDS_FT_MATCHES                  58105
#define IDS_FT_VALUE                    58106
#define IDS_FT_ANDOR                    58107
#define IDS_TDLBC_RECENTEDIT            58108
#define IDS_TDC_COLUMN_RECENTEDIT       58109
#define IDS_TDLBC_REMAINING             58110
#define IDS_SB_LISTTASKCOUNT            58111
#define IDS_SB_TASKCOUNT                58111
#define IDS_SB_TREETASKCOUNT            58112
#define IDS_SOUNDFILEFILTER             58112
#define IDS_SB_LISTTASKCOUNT_TIP        58113
#define IDS_TE_MINS                     58114
#define IDS_TE_HOURS                    58115
#define IDS_TE_DAYS                     58116
#define IDS_TE_WEEKS                    58117
#define IDS_TE_MONTHS                   58118
#define IDS_TE_YEARS                    58119
#define IDS_FILTER_ANYCATS              58120
#define IDS_FILTER_ANYPEOPLE            58121
#define IDS_FILTER_HIDEPARENTS          58122
#define IDS_FILTER_HIDEOVERDUE          58123
#define IDS_FILTER_HIDEDONE             58124
#define IDS_FILTER_HIDECOLLAPSED        58125
#define IDS_QUICKFIND                   58126
#define IDS_NOTASKSIMPORTED             58127
#define IDS_FT_SAVESEARCHPROMPT         58128
#define IDS_FILTER_ALL                  58129
#define IDS_FILTER_NOTDONE              58130
#define IDS_FILTER_DONE                 58131
#define IDS_FILTER_DUETODAY             58132
#define IDS_FILTER_DUETOMORROW          58133
#define IDS_FILTER_DUEENDTHISWEEK       58134
#define IDS_FILTER_DUEENDNEXTWEEK       58135
#define IDS_FILTER_DUEENDTHISMONTH      58136
#define IDS_FILTER_DUEENDNEXTMONTH      58137
#define IDS_FILTER_DUEENDTHISYEAR       58138
#define IDS_FILTER_DUEENDNEXTYEAR       58139
#define IDS_FILTER_DUENEXTSEVENDAYS     58140
#define IDS_FILTER_STARTTODAY           58141
#define IDS_FILTER_STARTENDTHISWEEK     58142
#define IDS_FILTER_STARTNEXTSEVENDAYS   58143
#define IDS_FILTER_FLAGGED              58144
#define IDS_BEGINWHENREMINDERHOURS      58145
#define IDS_DUEWHENREMINDERHOURS        58146
#define IDS_BEGINWHENREMINDERMINS       58147
#define IDS_DUEWHENREMINDERMINS         58148
#define IDS_TDC_FIELD_STARTTIME         58149
#define IDS_UITHEMEFILEFILTER           58150
#define IDS_NEEDRESTARTTODOLISTLIGHTBOXCHANGE 58151
#define IDS_NOONE                       58152
#define IDS_NOSTATUS                    58153
#define IDS_NOVERSION                   58154
#define IDS_FILTER_ACTIVE               58155
#define IDS_FILTER_NOTSTARTED           58156
#define IDS_PTDP_VERSION                58157
#define IDS_REUSE_RECURRING_TASK        58158
#define IDS_CANTCOMPLETEMULTIPLERECURRINGTASKS 58159
#define IDS_SD_SERVERLABEL              58160
#define IDS_SD_USERNAMELABEL            58161
#define IDS_SD_PASSWORDLABEL            58162
#define IDS_SCD_DICTLABEL               58163
#define IDS_SCD_BROWSE                  58164
#define IDS_SCD_URL                     58165
#define IDS_SCD_CHECKINGLABEL           58166
#define IDS_SCD_RESTART                 58167
#define IDS_SCD_REPLACELABEL            58168
#define IDS_SCD_WITHLABEL               58169
#define IDS_SCD_REPLACE                 58170
#define IDS_SCD_NEXT                    58171
#define IDS_SCD_TITLE                   58172
#define IDS_SD_TITLE                    58173
#define IDS_SCD_BROWSETITLE             58174
#define IDS_SCD_SETUPMSG                58175
#define IDS_SCD_DICTFILTER              58176
#define IDS_SCD_ENGINETITLE             58177
#define IDS_SCD_ENGINEFILTER            58178
#define IDS_SD_ANONLOGIN                58179
#define IDS_TDLBC_NAME                  58180
#define IDS_TDLBC_ICON                  58181
#define IDS_PREF_FILEMORE               58182
#define IDS_PREF_FILEBACKUP             58183
#define IDS_PLAYSOUNDBTNTIP             58184
#define IDS_TDC_FIELD_DONETIME          58185
#define IDS_TDLBC_REMINDER              58186
#define IDS_TIMEUNITS                   58187
#define IDS_BROWSE                      58188
#define IDS_VIEW                        58189
#define IDS_OPTIONS                     58190
#define IDS_COMMENTSCTRLCLICKMSG        58191
#define IDS_TDC_UPDATEFILTER_TIP        58192
#define IDS_CUSTOMFILTER                58193
#define IDS_LOGFILELOCKED               58194
#define IDS_FLAGGED                     58195
#define IDS_UNFLAGGED                   58196
#define IDS_DUEWHENREMINDERNOW          58197
#define IDS_BEGINWHENREMINDERNOW        58198
#define IDS_ONLINEHELPTITLE             58199
#define IDS_MISCSHORTCUTS               58200
#define IDS_TDLBC_PARENTID              58201
#define IDS_TDC_COLUMN_PARENTID         58202
#define IDS_CSV_COLUMNNAME              58203
#define IDS_CSV_MAPSTOATTRIBUTE         58204
#define IDS_CSV_ATTRIBUTE               58205
#define IDS_CSV_MAPSTOCOLUMNNAME        58206
#define IDS_TDLBC_COLOR                 58207
#define IDS_TDLBC_PROJECTNAME           58208
#define IDS_CSV_EXPORTDLG               58210
#define IDS_CSV_IMPORTDLG               58211
#define IDS_SB_FOCUS_TIP                58212
#define IDS_SB_SELCOUNT_TIP             58213
#define IDS_SB_SELTIMEEST_TIP           58214
#define IDS_SB_SELTIMESPENT_TIP         58215
#define IDS_SB_SELCOST_TIP              58216
#define IDS_SB_FILEVERSION_TIP          58217
#define IDS_SB_TASKCOUNT_TIP            58218
#define IDS_SB_FILEPATH_TIP             58219
#define IDS_IMPORTFILE_CANTOPEN         58220
#define IDS_TDLBC_TASKPARENTIDS         58221

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         33264
#define _APS_NEXT_CONTROL_VALUE         1325
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
