// BCApplet dynamic-link library.
// Copyright (c) 1999-2005 by Jan van den Baard,
// All rights reserved.

// stdafx.h - include file for standard system include files

// initially generated by AfxScratch v1.0.3839 on 03.04.2008 at 09:52:50
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__stdafx_h)
#define __stdafx_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif	// _MSC_VER

// unreferenced inline/local function has been removed
#pragma warning(disable: 4514)
// function not inlined
#pragma warning(disable: 4710)
// identifier was truncated in the debug information
#pragma warning(disable: 4786)

// Use Windows 2000 and IE 6.0 features
#define WINVER 0x0500
#define _WIN32_WINDOWS 0x0410
#define _WIN32_IE 0x0600
#define _WIN32_WINNT 0x0500

// PSDK headers
#pragma warning(push, 3)
#include <windows.h>
#include <custcntl.h>
#include <commdlg.h>
#include <commctrl.h>
#include <ole2.h>
#include <shlwapi.h>
#include <cpl.h>
#pragma warning(pop)

// CRT headers
#include <tchar.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <crtdbg.h>
#include <limits.h>

// force ISO/IEC 14882 conformance in for loop scope
#if (_MSC_VER < 1300)
#define for if (false); else for
#else
#pragma conform(forScope, on)
#endif	// _MSC_VER

#endif	// __stdafx_h

// end of file
