// XPControls application.
// Copyright (c) 2008 by Jan van den Baard,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes

// initially generated by AfxScratch v1.0.3839 on 11.04.2008 at 12:16:25
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#include "stdafx.h"

#if defined(_MSC_VER) && (_MSC_VER < 1300)
#pragma comment(linker, "/ignore:4089")		// all references to DLL discarded by /opt:ref
#endif	// _MSC_VER

// end of file
